Pc/urls.py
from django.contrib import admin
from django.urls import path,include
from Pc import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('polls/',include('polls.urls')),
    path('tasks/',include('tasks.urls')),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

from app1.models import User,Event
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    # instead of showwind "True/False" in this def, it showing icon and also provide filtering 
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.ManyToManyField(User,related_name='vote_usr',blank=True)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Question, Choice
from app1.models import User

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last 5 published questions not including
        those set to be published in the future
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:3]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # redisplaying the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Please select atleast one option!'
        })
    else:
        try:
            user = request.session['user_email']
            user1 = User.objects.filter(pk=user).get()
            selected_choice.votes.add(user1)
        except:
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': 'Please login..!'
            })
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% extends 'polls/layout.html' %}

{% block title %}Details{% endblock title %}

{% block body %}
<div class="container" align="center">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-arrow-right"></span>{{ question.question_text }}
                    </h3>
                </div>

{% if error_message %}
<p><strong> {{ error_message }} </strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
<div class="panel-body">
                    <ul class="list-group">
    {% for choice in question.choice_set.all %}

                        <li class="list-group-item">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id }}">
        {{ choice.choice_text }}</label>

                            </div>
                        </li>



    {% endfor %}</ul>
                </div>
    <input type="submit" value="Vote" class="btn btn-primary btn-sm">
</form>
{% endblock body %}

polls/templates/polls/index.html
{% extends 'polls/layout.html' %}

{% block title %}Polls{% endblock title %}

{% block body %}


<div class="container" align="center">
    <div class="row">
        {% for question in latest_question_list %}
        <div class="col-md-3">
            <div class="panel panel-primary"><br><br>
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-arrow-right"></span>{{ question.question_text }}</span>
                    </h3>
                </div>

        <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}


    <div class="panel-body">
                    <ul class="list-group">
                        {% for choice in question.choice_set.all %}
                        <li class="list-group-item">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id }}">
        {{ choice.choice_text }}</label>

                            </div>
                        </li>




        {% endfor %}</ul>
                </div><input type="submit" value="Vote" class="btn btn-primary btn-sm">
        </form></div></div>
            {%endfor%}
                </div>



{% endblock body %}

polls/templates/polls/layout.html
{% extends  'navbar_temp.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% block extra_css %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
    <title>
        {% block title %}

        {% endblock title %}
    </title>
</head>
{%endblock%}
{% block navbar_wrap %}
<body align="center">
    <div style="padding:4rem;align:center;">
        <span style="text-align: center;font-size: 7vh; text-align: left !important;">Polls</span>
        {% block body %}

        {% endblock body %}
    </div>

</body>
{% endblock%}
</html>

polls/templates/polls/results.html
{% extends 'polls/layout.html' %}


{% block title %}
Results
{% endblock title %}

</head>

{% block body %}
<div class="container" align="center">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-arrow-right"></span>{{ question.question_text }}
                    </h3>
                </div>
<ul>
    <div class="panel-body">
                    <ul class="list-group">
    {% for choice in question.choice_set.all  %}

                        <li class="list-group-item">
                            <div class="radio">

            {{ choice.choice_text }} - {{ choice.votes.count }} vote{{ choice.votes|pluralize }}
        </div>
                        </li>


    {% endfor %}
                         </ul>
                </div>

</ul>
            </div></div></div></div>


{% endblock body %}